signatures:
  AWS Access Key:
    pattern: AKIA[0-9A-Z]{16}
    weight: 30
  AWS Secret Key:
    pattern: (?i)aws(.{0,20})?(secret|private)?(.{0,20})?['\"][0-9a-zA-Z/+]{40}['\"]
    weight: 50
  Google API Key:
    pattern: AIza[0-9A-Za-z\-_]{35}
    weight: 25
  Private Key:
    pattern: '-----BEGIN(.*?)PRIVATE KEY-----'
    weight: 70
  Basic Auth:
    pattern: '[a-zA-Z0-9_\-]{3,20}:[a-zA-Z0-9_\-!@#\$%\^&\*]{3,20}'
    weight: 20
  JWT Token:
    pattern: eyJ[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+
    weight: 35
  Heroku API Key:
    pattern: (?i)heroku(.{0,20})?['\"][0-9a-fA-F]{32}['\"]
    weight: 30
  Slack Token:
    pattern: xox[baprs]-[0-9a-zA-Z]{10,48}
    weight: 25
  Mongo URI:
    pattern: mongodb(\+srv)?:\/\/[^ \n]+
    weight: 30
  Generic Token:
    pattern: (?i)(bearer\s+|token\s+)?[A-Za-z0-9_\-]{32,45}
    weight: 15
  S3 URL:
    pattern: (s3[.-](?:amazonaws|external|dualstack|website)[^\s"']+|s3://[^\s"']+)
    weight: 20
  .env / Config File Mention:
    pattern: (?i)(\.env|config|auth_token|access_token|client_secret|client_id|secret|password|credentials|authorization)
    weight: 10
  Database URL:
    pattern: (postgres|mysql|mongodb|redis):\/\/[^\s]+
    weight: 25
  Google Cloud Service Account:
    pattern: '"type":\s*"service_account"'
    weight: 40
  Facebook Access Token:
    pattern: EAACEdEose0cBA[0-9A-Za-z]+
    weight: 30
  Stripe API Key:
    pattern: sk_live_[0-9a-zA-Z]{24}
    weight: 30
  Twilio API Key:
    pattern: SK[0-9a-fA-F]{32}
    weight: 30
  SendGrid API Key:
    pattern: SG\.[a-zA-Z0-9_\-]{22}\.[a-zA-Z0-9_\-]{43}
    weight: 30
  Github Token:
    pattern: ghp_[A-Za-z0-9_]{36,}
    weight: 30
  JSON Web Key:
    pattern: '"kty":\s*"RSA"'
    weight: 35
